"""add balance to player_to_session

Revision ID: 01e337ff948e
Revises: cb9c9b9b7bf4
Create Date: 2026-03-13 18:03:59.408015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e337ff948e'
down_revision: Union[str, None] = 'cb9c9b9b7bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_to_session', sa.Column('balance', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_players_telegram_id'), table_name='players')
    op.create_index(op.f('ix_players_telegram_id'), 'players', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_telegram_id'), table_name='players')
    op.create_index(op.f('ix_players_telegram_id'), 'players', ['telegram_id'], unique=False)
    op.drop_column('player_to_session', 'balance')
    # ### end Alembic commands ###
