"""remove balance from player_to_session

Revision ID: 60d60fc1454d
Revises: 36a448a229f9
Create Date: 2026-03-13 21:44:13.477221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d60fc1454d'
down_revision: Union[str, None] = '36a448a229f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_to_session', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_to_session', sa.Column('balance', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
