"""initial

Revision ID: cb9c9b9b7bf4
Revises: 
Create Date: 2026-03-12 18:03:35.212309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9c9b9b7bf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_chat_id'), 'decks', ['chat_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=False),
    sa.Column('bank', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_players_telegram_id', 'players', ['telegram_id'], unique=False)
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting_for_players', 'active', 'closed', name='sessionstatus'), nullable=False),
    sa.Column('count_players', sa.Integer(), nullable=False),
    sa.Column('dealer_cards', sa.JSON(), nullable=False),
    sa.Column('dealer_bet', sa.BigInteger(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('current_timer', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_sessions_deck_id', 'game_sessions', ['deck_id'], unique=False)
    op.create_index('uq_active_session_per_deck', 'game_sessions', ['deck_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('player_to_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('bet', sa.BigInteger(), nullable=False),
    sa.Column('cards', sa.JSON(), nullable=False),
    sa.CheckConstraint('position >= 1 AND position <= 8', name='ck_player_position_range'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_session_position')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.CheckConstraint('position >= 1 AND position <= 8', name='ck_state_position_range'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    op.drop_table('player_to_session')
    op.drop_index('uq_active_session_per_deck', table_name='game_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_game_sessions_deck_id', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index('ix_players_telegram_id', table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_decks_chat_id'), table_name='decks')
    op.drop_table('decks')
    # ### end Alembic commands ###
